apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # or the appropriate storage class for your cluster
